#' @title Selection of ions with sufficient imaging signals
#'
#' @description If the intensity of the 12C-metabolite ion is found to be less
#'     than the set minimum count in a specific number of samples, this ion and
#'     its corresponding isotopologue group will be removed.
#'
#' @param df The table generated by the first step.
#' @param Intensity The minimum counts required for ions to be imaged.
#' @param num The number of samples reaching the set imaging counts threshold.
#'
#' @return An updated table.
#' @export
#'
#' @examples Scanint(Target,Intensity=100, num=2)
Scanint <- function(df, Intensity=100, num=2){
  remove_ids <- NULL

  select_df <- df[df$IsotopeLabel == "C12 PARENT", ]
  for(row in 1:nrow(select_df)){
    if(sum(select_df[row, c("Unlabel_01", "Unlabel_02", "Unlabel_03", "Glc_Label_01", "Glc_Label_02", "Glc_Label_03")] < Intensity) > num){
      remove_ids <- c(remove_ids, unlist(select_df[row, "ID"]))
    }
  }

  remain_df <- df[df$ID %in% remove_ids == F, ]
  return(remain_df)
}
